[package]
name = "ephact-infrastructure"
version = "0.3.0"
edition = "2024"

[dependencies]
serde_yaml = "0.9"
serde_json = "1"
toml = "0.8"
uuid = { version = "1.23.4", features = ["v4"] }
bytes = "1"
libc = "0.2.189"
futures-util = "0.3.33"
tar = "0.4.46"
bollard = "0.21.0"
tokio = { version = "1.53.1", features = ["full"] }
thiserror = "2.0.18"
serde = { version = "1", features = ["derive"] }

# Dependencies on the domain layer
ephact-domain = { path = "../domain", version = "0.3.0" }

# Dependencies on the application layer
ephact-application = { path = "../application", version = "0.3.0" }

[dev-dependencies]
serde_json = "1"
tempfile = "3"

[features]
container-integration = []