[package]
name = "ephact"
version = "0.1.0"
edition = "2024"
description = "Runs actions and workflows locally in ephemeral repositories, isolated from your operating system."
license = "MIT OR Apache-2.0"

[dependencies]
chrono = "0.4.45"
thiserror = "2.0.18"
uuid = { version = "1.23.4", features = ["v4"] }
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
serde_json = "1"
bollard = "0.21.0"
tokio = { version = "1.53.1", features = ["full"] }
tar = "0.4.46"
futures-util = "0.3.33"
libc = "0.2.189"
bytes = "1"

[dev-dependencies]
parking_lot = "0.12"
tempfile = "3"

[[test]]
name = "application"
path = "tests/application/mod.rs"

[[test]]
name = "infrastructure"
path = "tests/infrastructure/mod.rs"

[[test]]
name = "presentation"
path = "tests/presentation/mod.rs"

[[test]]
name = "e2e"
path = "tests/e2e/mod.rs"
