[git]
conventional_commits = true
filter_unconventional = true
deduplicate_commits = true

commit_parsers = [
  { message = "^\\w+\\(.*\\)!:", breaking = true, group = "<!-- 0 -->Breaking Changes" },
  { message = "^\\w+!:", breaking = true, group = "<!-- 0 -->Breaking Changes" },
  { body = "BREAKING CHANGE", breaking = true, group = "<!-- 0 -->Breaking Changes" },
  { message = "^feat", group = "<!-- 1 -->Features" },
  { message = "^fix", group = "<!-- 2 -->Bug Fixes" },
  { message = "^refactor", group = "<!-- 3 -->Refactor" },
  { message = "^perf", group = "<!-- 4 -->Performance" },
  { message = "^docs?", group = "<!-- 5 -->Documentation" },
  { message = "^test", group = "<!-- 6 -->Testing" },
  { message = "^ci", group = "<!-- 7 -->Continuous Integration" },
  { message = "^chore\\(release\\)", skip = true },
  { message = "^chore\\(cliff\\)", skip = true },
  { message = "Prepare release", skip = true },
  { message = "^chore", group = "<!-- 7 -->Miscellaneous Tasks" },
  { message = ".*", skip = true },
]

[changelog]
output = "CHANGELOG.md"

body = """
{% if version %}\
    ## [{{ version | trim_start_matches(pat=\"v\") }}] - {{ timestamp | date(format=\"%Y-%m-%d\") }}
{% else %}\
    ## [Unreleased]
{% endif %}\
{% for group, commits in commits | group_by(attribute=\"group\") %}
    ### {{ group | striptags }}
    {% for commit in commits %}
        - {% if commit.scope %}**{{ commit.scope }}**: {% endif %}\
          {% if commit.breaking %}[BREAKING] {% endif %}\
          {{ commit.message | upper_first }}\
    {% endfor %}
{% endfor %}
"""

sort_commits = "oldest"
limit_releases = 0
