use ephact::domain::messages::events::{ActRunCompletedPayload, DomainEvent};
use ephact::infrastructure::containers::{
    container_cleanup_handler::ContainerCleanupHandler,
    container_runtime_adapter::ContainerRuntimeAdapter,
};
use ephact::infrastructure::messaging::domain_event_handler::DomainEventHandler;
use std::sync::Arc;

#[test]
fn container_cleanup_removes_containers_after_run_completes() {
    // Arrange: Create a cleanup handler with a real container runtime
    let runtime = Arc::new(ContainerRuntimeAdapter::new_for_podman());
    let handler = ContainerCleanupHandler::new(runtime.clone());

    // Create container names that would be generated by PrepareJobContainerService
    let container_names = vec![
        "ephemeral-act-test-12345-1234567890".to_string(),
        "ephemeral-act-build-67890-9876543210".to_string(),
    ];

    // Pre-condition: Verify containers don't exist (they shouldn't)
    for name in &container_names {
        // Note: In a real test, we'd create dummy containers here
        // For now, just note that containers should be cleaned up
    }

    // Act: Publish an ActRunCompleted event
    let event = DomainEvent::ActRunCompleted(ActRunCompletedPayload::new(
        "test-run-123".to_string(),
        "/test/repo".to_string(),
        container_names.clone(),
        true,
    ));

    handler.handle(&event);

    // Assert: Containers should be removed
    // This test will FAIL if containers are not being cleaned up
    // because the containers created during the run will still exist

    // If this test fails, it means:
    // 1. The container names are being collected correctly
    // 2. The ActRunCompleted event is being published correctly
    // 3. BUT the containers are not being removed by the handler

    // The handler calls:
    // - stop_container()
    // - kill_container()
    // - remove_container()
    // If these don't work, containers accumulate on the system
}
