[package]
name = "ephact-application"
version = "0.3.0"
edition = "2024"
description = "Application layer of ephact: application services, ports and DTOs."
license = "MIT OR Apache-2.0"

[dependencies]
thiserror = "2.0.18"
serde_yaml = "0.9"

# Dependencies on the domain layer
ephact-domain = { path = "../domain", version = "0.3.0" }


[features]
container-integration = []